### ISSUE TITLE
Define KMS API

### ISSUE THREAD

**Issue by awoie** [uport-project/veramo#468]
1. KMS API should support low-level crypto API, also including those required for ECDH-1PU:
- sign
- sharedSecret(myPrivKeyHandle, publicKeyRecipient, 'X25519')
- ... 
2. Each `AbstractKeyManagementSystem` implementation should be in charge of storing the private key material, instead of relying on `@veramo/key-manager` for storage. Private keys should not be exposed between plugins.

pre-work here: https://whimsical.com/crypto-suites-kms-link-BycG8ABUoV3L4MEGUkHTfG

**Comment by mirceanis** [comment]
TODO:
* [ ] remove privateKey references from `IKey` interface. key material should not leak outside the KMS that manages it
* [ ] redefine low level crypto methods that can be provided (`sign`, `decrypt`, `sharedSecret`, please comment if you can think of another one)
* [ ] KMS layer should report which plugins it supports, and add this metadata to the `IKey` during create/import.
* [ ] create a localStorage plugin interface that can be used by the new KeyManager ( and possibly DIDManager ) to persist the links between kid and KMS implementations
* [ ] explore the decoupling of the database storage from key storage (perhaps using an encryption layer on top of the localStorage plugin)
* [ ] ensure easy migration path from `@veramo/key-manager` with `dbConnection` to the new system.

**Comment by mirceanis** [comment]
I'm splitting this up into parts so that other work is not blocked for the whole duration of this implementation.
1. expose the `sign`, `decrypt`, `sharedSecret` methods on the current key-manager to unblock other tasks
2. continue working on the refactoring
3. adapt other plugins to the potentially new API after refactoring.

**Comment by mirceanis** [comment]
Closed by #529
